// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/liquidity/add/[[...poolId]]": InferRoute<import("./src/pages/liquidity/add/[[...poolId]]").RouteType>;
    "/liquidity/create/[...selectId]": InferRoute<import("./src/pages/liquidity/create/[...selectId]").RouteType>;
    "/liquidity/position/[[...positionId]]": InferRoute<import("./src/pages/liquidity/position/[[...positionId]]").RouteType>;
    "/liquidity/select/[[...selectId]]": InferRoute<import("./src/pages/liquidity/select/[[...selectId]]").RouteType>;
    "/liquidity/select/pools/[[...selectId]]": InferRoute<import("./src/pages/liquidity/select/pools/[[...selectId]]").RouteType>;
  }

  interface StaticRouter {
    "/404": StaticRoute;
    "/451": StaticRoute;
    "/add/[[...currency]]": StaticRoute;
    "/find": StaticRoute;
    "/home": StaticRoute;
    "/increase/[[...currency]]": StaticRoute;
    "/": StaticRoute;
    "/info/[chainName]": StaticRoute;
    "/info/[chainName]/pairs/[address]": StaticRoute;
    "/info/[chainName]/pairs": StaticRoute;
    "/info/[chainName]/tokens/[address]": StaticRoute;
    "/info/[chainName]/tokens": StaticRoute;
    "/info": StaticRoute;
    "/info/infinity/[chainName]": StaticRoute;
    "/info/infinity/[chainName]/pairs": StaticRoute;
    "/info/infinity/[chainName]/tokens/[address]": StaticRoute;
    "/info/infinity/[chainName]/tokens": StaticRoute;
    "/info/infinity": StaticRoute;
    "/info/infinity/tokens/[address]": StaticRoute;
    "/info/infinity/tokens": StaticRoute;
    "/info/pairs/[address]": StaticRoute;
    "/info/pairs": StaticRoute;
    "/info/tokens/[address]": StaticRoute;
    "/info/tokens": StaticRoute;
    "/info/v3/[chainName]": StaticRoute;
    "/info/v3/[chainName]/pairs/[address]": StaticRoute;
    "/info/v3/[chainName]/pairs": StaticRoute;
    "/info/v3/[chainName]/tokens/[address]": StaticRoute;
    "/info/v3/[chainName]/tokens": StaticRoute;
    "/info/v3": StaticRoute;
    "/info/v3/pairs/[address]": StaticRoute;
    "/info/v3/pairs": StaticRoute;
    "/info/v3/tokens/[address]": StaticRoute;
    "/info/v3/tokens": StaticRoute;
    "/liquidity/[tokenId]": StaticRoute;
    "/liquidity/create": StaticRoute;
    "/liquidity": StaticRoute;
    "/liquidity/pool/[chainName]/[id]": StaticRoute;
    "/liquidity/pools": StaticRoute;
    "/liquidity/positions": StaticRoute;
    "/remove/[tokenId]": StaticRoute;
    "/swap": StaticRoute;
  }
}
